CREATE DATABASE IF NOT EXISTS omie_db
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE omie_db;

CREATE TABLE IF NOT EXISTS raw_omie_paises (
  codigo_pais VARCHAR(20) NOT NULL,
  codigo_iso CHAR(2) NULL,
  descricao VARCHAR(120) NULL,
  dados_json JSON NOT NULL,
  dados_flat_json JSON NOT NULL,
  extraido_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (codigo_pais),
  KEY idx_raw_omie_paises_codigo_iso (codigo_iso),
  KEY idx_raw_omie_paises_descricao (descricao)
)
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS raw_omie_clientes (
  codigo_cliente_omie BIGINT NOT NULL,
  codigo_cliente_integracao VARCHAR(120) NULL,
  cnpj_cpf VARCHAR(30) NULL,
  razao_social VARCHAR(200) NULL,
  nome_fantasia VARCHAR(200) NULL,
  email VARCHAR(241) NULL,
  telefone1_ddd VARCHAR(10) NULL,
  telefone1_numero VARCHAR(30) NULL,
  cidade VARCHAR(80) NULL,
  estado VARCHAR(80) NULL,
  cep VARCHAR(20) NULL,
  endereco VARCHAR(160) NULL,
  endereco_numero VARCHAR(20) NULL,
  bairro VARCHAR(80) NULL,
  inativo CHAR(1) NULL,
  bloquear_faturamento CHAR(1) NULL,
  cidade_ibge VARCHAR(20) NULL,
  codigo_pais VARCHAR(20) NULL,
  complemento VARCHAR(160) NULL,
  contato VARCHAR(160) NULL,
  enviar_anexos CHAR(1) NULL,
  exterior CHAR(1) NULL,
  homepage VARCHAR(255) NULL,
  inscricao_estadual VARCHAR(30) NULL,
  inscricao_municipal VARCHAR(30) NULL,
  optante_simples_nacional CHAR(1) NULL,
  pessoa_fisica CHAR(1) NULL,
  banco_codigo VARCHAR(20) NULL,
  banco_agencia VARCHAR(30) NULL,
  banco_conta_corrente VARCHAR(40) NULL,
  banco_chave_pix VARCHAR(255) NULL,
  banco_documento_titular VARCHAR(30) NULL,
  banco_nome_titular VARCHAR(200) NULL,
  banco_transferencia_padrao CHAR(1) NULL,
  dados_bancarios_json JSON NULL,
  endereco_entrega_json JSON NULL,
  recomendacoes_gerar_boletos CHAR(1) NULL,
  recomendacoes_json JSON NULL,
  omie_importado_api CHAR(1) NULL,
  omie_data_inclusao VARCHAR(10) NULL,
  omie_hora_inclusao VARCHAR(8) NULL,
  omie_usuario_inclusao VARCHAR(80) NULL,
  omie_data_alteracao VARCHAR(10) NULL,
  omie_hora_alteracao VARCHAR(8) NULL,
  omie_usuario_alteracao VARCHAR(80) NULL,
  info_json JSON NULL,
  tags TEXT NULL,
  tags_json JSON NOT NULL,
  dados_json JSON NOT NULL,
  dados_flat_json JSON NOT NULL,
  extraido_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (codigo_cliente_omie),
  KEY idx_raw_omie_clientes_cnpj_cpf (cnpj_cpf),
  KEY idx_raw_omie_clientes_integracao (codigo_cliente_integracao),
  KEY idx_raw_omie_clientes_codigo_pais (codigo_pais),
  CONSTRAINT fk_raw_omie_clientes_pais
    FOREIGN KEY (codigo_pais)
    REFERENCES raw_omie_paises (codigo_pais)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
)
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS raw_omie_clientes_caracteristicas (
  id BIGINT NOT NULL AUTO_INCREMENT,
  codigo_cliente_omie BIGINT NOT NULL,
  codigo_cliente_integracao VARCHAR(60) NULL,
  numero_sequencia INT NOT NULL,
  campo VARCHAR(30) NULL,
  conteudo VARCHAR(60) NULL,
  caracteristica_json JSON NOT NULL,
  resposta_json JSON NOT NULL,
  dados_flat_json JSON NOT NULL,
  extraido_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_raw_omie_cli_caract_cliente (codigo_cliente_omie),
  KEY idx_raw_omie_cli_caract_campo (campo),
  CONSTRAINT fk_raw_omie_cli_caract_cliente
    FOREIGN KEY (codigo_cliente_omie)
    REFERENCES raw_omie_clientes (codigo_cliente_omie)
    ON UPDATE CASCADE
    ON DELETE CASCADE
)
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS raw_omie_clientes_tags (
  id BIGINT NOT NULL AUTO_INCREMENT,
  codigo_cliente_omie BIGINT NOT NULL,
  codigo_cliente_integracao VARCHAR(120) NULL,
  numero_sequencia INT NOT NULL,
  codigo_tag BIGINT NULL,
  tag VARCHAR(120) NULL,
  tag_json JSON NOT NULL,
  resposta_json JSON NOT NULL,
  dados_flat_json JSON NOT NULL,
  extraido_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_raw_omie_cli_tags_cliente (codigo_cliente_omie),
  KEY idx_raw_omie_cli_tags_codigo_tag (codigo_tag),
  KEY idx_raw_omie_cli_tags_tag (tag),
  CONSTRAINT fk_raw_omie_cli_tags_cliente
    FOREIGN KEY (codigo_cliente_omie)
    REFERENCES raw_omie_clientes (codigo_cliente_omie)
    ON UPDATE CASCADE
    ON DELETE CASCADE
)
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS raw_omie_empresas (
  codigo_empresa BIGINT NOT NULL,
  cnpj VARCHAR(30) NULL,
  razao_social VARCHAR(200) NULL,
  nome_fantasia VARCHAR(200) NULL,
  email VARCHAR(241) NULL,
  telefone1_ddd VARCHAR(10) NULL,
  telefone1_numero VARCHAR(30) NULL,
  telefone2_ddd VARCHAR(10) NULL,
  telefone2_numero VARCHAR(30) NULL,
  fax_ddd VARCHAR(10) NULL,
  fax_numero VARCHAR(30) NULL,
  website VARCHAR(255) NULL,
  cidade VARCHAR(100) NULL,
  estado VARCHAR(80) NULL,
  cep VARCHAR(20) NULL,
  endereco VARCHAR(160) NULL,
  endereco_numero VARCHAR(20) NULL,
  bairro VARCHAR(80) NULL,
  complemento VARCHAR(160) NULL,
  logradouro VARCHAR(160) NULL,
  codigo_pais VARCHAR(20) NULL,
  cnae VARCHAR(20) NULL,
  cnae_municipal VARCHAR(30) NULL,
  inscricao_estadual VARCHAR(30) NULL,
  inscricao_municipal VARCHAR(30) NULL,
  inscricao_suframa VARCHAR(30) NULL,
  regime_tributario VARCHAR(20) NULL,
  optante_simples_nacional CHAR(1) NULL,
  gera_nfse CHAR(1) NULL,
  inativa CHAR(1) NULL,
  pdv_sincr_analitica CHAR(1) NULL,
  csc_homologacao VARCHAR(255) NULL,
  csc_id_homologacao VARCHAR(80) NULL,
  csc_producao VARCHAR(255) NULL,
  csc_id_producao VARCHAR(80) NULL,
  ecd_codigo_cadastral VARCHAR(80) NULL,
  ecd_codigo_instituicao_responsavel VARCHAR(80) NULL,
  efd_atividade_industrial VARCHAR(80) NULL,
  efd_perfil_arquivo_fiscal VARCHAR(80) NULL,
  sped_codigo_criterio_escrituracao VARCHAR(80) NULL,
  sped_codigo_incidencia_tributaria VARCHAR(80) NULL,
  sped_codigo_indicador_apropriacao_credito VARCHAR(80) NULL,
  sped_codigo_tipo_atividade VARCHAR(80) NULL,
  sped_codigo_tipo_contribuicao VARCHAR(80) NULL,
  sped_cpf_contador VARCHAR(30) NULL,
  sped_crc_contador VARCHAR(80) NULL,
  sped_email_contador VARCHAR(241) NULL,
  sped_junta_comercial VARCHAR(80) NULL,
  sped_matriz VARCHAR(80) NULL,
  sped_natureza_pessoa_juridica VARCHAR(80) NULL,
  sped_nome_contador VARCHAR(200) NULL,
  sped_registro_junta_comercial VARCHAR(80) NULL,
  sped_usa_contabilidade_terceirizada VARCHAR(80) NULL,
  pagina_api INT NULL,
  total_de_paginas_api INT NULL,
  registros_api INT NULL,
  total_de_registros_api INT NULL,
  produto_servico_resumido_json JSON NOT NULL,
  dados_json JSON NOT NULL,
  dados_flat_json JSON NOT NULL,
  extraido_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (codigo_empresa),
  KEY idx_raw_omie_empresas_cnpj (cnpj),
  KEY idx_raw_omie_empresas_razao_social (razao_social)
)
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS raw_omie_bancos (
  codigo VARCHAR(20) NOT NULL,
  nome VARCHAR(200) NULL,
  tipo VARCHAR(20) NULL,
  pagina_api INT NULL,
  total_de_paginas_api INT NULL,
  registros_api INT NULL,
  total_de_registros_api INT NULL,
  dados_json JSON NOT NULL,
  dados_flat_json JSON NOT NULL,
  extraido_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (codigo),
  KEY idx_raw_omie_bancos_nome (nome),
  KEY idx_raw_omie_bancos_tipo (tipo)
)
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS raw_omie_cidades (
  codigo VARCHAR(120) NOT NULL,
  nome VARCHAR(120) NULL,
  uf CHAR(2) NULL,
  codigo_ibge VARCHAR(20) NULL,
  codigo_siafi INT NULL,
  pagina_api INT NULL,
  total_de_paginas_api INT NULL,
  registros_api INT NULL,
  total_de_registros_api INT NULL,
  dados_json JSON NOT NULL,
  dados_flat_json JSON NOT NULL,
  extraido_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (codigo),
  KEY idx_raw_omie_cidades_nome (nome),
  KEY idx_raw_omie_cidades_uf (uf),
  KEY idx_raw_omie_cidades_ibge (codigo_ibge)
)
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS raw_omie_contas_pagar (
  codigo_lancamento_omie BIGINT NOT NULL,
  codigo_lancamento_integracao VARCHAR(120) NULL,
  codigo_cliente_fornecedor BIGINT NOT NULL,
  codigo_categoria VARCHAR(40) NULL,
  codigo_tipo_documento VARCHAR(20) NULL,
  codigo_projeto BIGINT NULL,
  id_conta_corrente BIGINT NULL,
  id_origem VARCHAR(20) NULL,
  numero_documento VARCHAR(120) NULL,
  numero_documento_fiscal VARCHAR(120) NULL,
  numero_parcela VARCHAR(30) NULL,
  codigo_barras_ficha_compensacao VARCHAR(255) NULL,
  data_emissao VARCHAR(10) NULL,
  data_entrada VARCHAR(10) NULL,
  data_previsao VARCHAR(10) NULL,
  data_vencimento VARCHAR(10) NULL,
  valor_documento DECIMAL(18, 4) NULL,
  valor_cofins DECIMAL(18, 4) NULL,
  valor_csll DECIMAL(18, 4) NULL,
  valor_ir DECIMAL(18, 4) NULL,
  valor_iss DECIMAL(18, 4) NULL,
  valor_pis DECIMAL(18, 4) NULL,
  retem_cofins CHAR(1) NULL,
  retem_csll CHAR(1) NULL,
  retem_inss CHAR(1) NULL,
  retem_ir CHAR(1) NULL,
  retem_iss CHAR(1) NULL,
  retem_pis CHAR(1) NULL,
  status_titulo VARCHAR(40) NULL,
  bloqueado CHAR(1) NULL,
  baixa_bloqueada CHAR(1) NULL,
  bloquear_exclusao CHAR(1) NULL,
  cnab_codigo_forma_pagamento VARCHAR(20) NULL,
  cnab_codigo_barras_boleto VARCHAR(255) NULL,
  cnab_juros_boleto DECIMAL(18, 4) NULL,
  cnab_multa_boleto DECIMAL(18, 4) NULL,
  cnab_pix_qrcode TEXT NULL,
  cnab_banco_transferencia VARCHAR(20) NULL,
  cnab_agencia_transferencia VARCHAR(30) NULL,
  cnab_conta_corrente_transferencia VARCHAR(60) NULL,
  cnab_cpf_cnpj_transferencia VARCHAR(30) NULL,
  cnab_nome_transferencia VARCHAR(200) NULL,
  cnab_finalidade_transferencia VARCHAR(80) NULL,
  omie_importado_api CHAR(1) NULL,
  omie_data_inclusao VARCHAR(10) NULL,
  omie_hora_inclusao VARCHAR(8) NULL,
  omie_usuario_inclusao VARCHAR(80) NULL,
  omie_data_alteracao VARCHAR(10) NULL,
  omie_hora_alteracao VARCHAR(8) NULL,
  omie_usuario_alteracao VARCHAR(80) NULL,
  pagina_api INT NULL,
  total_de_paginas_api INT NULL,
  registros_api INT NULL,
  total_de_registros_api INT NULL,
  categorias_json JSON NOT NULL,
  distribuicao_json JSON NOT NULL,
  cnab_integracao_bancaria_json JSON NOT NULL,
  info_json JSON NOT NULL,
  dados_json JSON NOT NULL,
  dados_flat_json JSON NOT NULL,
  extraido_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (codigo_lancamento_omie),
  KEY idx_raw_omie_cp_fornecedor (codigo_cliente_fornecedor),
  KEY idx_raw_omie_cp_categoria (codigo_categoria),
  KEY idx_raw_omie_cp_conta_corrente (id_conta_corrente),
  KEY idx_raw_omie_cp_projeto (codigo_projeto),
  KEY idx_raw_omie_cp_tipo_documento (codigo_tipo_documento),
  KEY idx_raw_omie_cp_status (status_titulo),
  KEY idx_raw_omie_cp_vencimento (data_vencimento),
  CONSTRAINT fk_raw_omie_cp_fornecedor
    FOREIGN KEY (codigo_cliente_fornecedor)
    REFERENCES raw_omie_clientes (codigo_cliente_omie)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
)
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS raw_omie_contas_receber (
  codigo_lancamento_omie BIGINT NOT NULL,
  codigo_lancamento_integracao VARCHAR(120) NULL,
  codigo_cliente_fornecedor BIGINT NOT NULL,
  codigo_categoria VARCHAR(40) NULL,
  codigo_tipo_documento VARCHAR(20) NULL,
  codigo_projeto BIGINT NULL,
  id_conta_corrente BIGINT NULL,
  id_origem VARCHAR(20) NULL,
  n_cod_os BIGINT NULL,
  numero_documento VARCHAR(120) NULL,
  numero_documento_fiscal VARCHAR(120) NULL,
  numero_parcela VARCHAR(30) NULL,
  numero_pedido VARCHAR(120) NULL,
  operacao VARCHAR(40) NULL,
  tipo_agrupamento VARCHAR(20) NULL,
  data_emissao VARCHAR(10) NULL,
  data_previsao VARCHAR(10) NULL,
  data_registro VARCHAR(10) NULL,
  data_vencimento VARCHAR(10) NULL,
  valor_documento DECIMAL(18, 4) NULL,
  valor_ir DECIMAL(18, 4) NULL,
  retem_cofins CHAR(1) NULL,
  retem_csll CHAR(1) NULL,
  retem_inss CHAR(1) NULL,
  retem_ir CHAR(1) NULL,
  retem_iss CHAR(1) NULL,
  retem_pis CHAR(1) NULL,
  status_titulo VARCHAR(40) NULL,
  bloqueado CHAR(1) NULL,
  bloquear_baixa CHAR(1) NULL,
  bloquear_exclusao CHAR(1) NULL,
  boleto_gerado CHAR(1) NULL,
  boleto_numero_bancario VARCHAR(80) NULL,
  boleto_numero VARCHAR(80) NULL,
  boleto_data_emissao VARCHAR(10) NULL,
  boleto_percentual_juros DECIMAL(18, 4) NULL,
  boleto_percentual_multa DECIMAL(18, 4) NULL,
  omie_importado_api CHAR(1) NULL,
  omie_data_inclusao VARCHAR(10) NULL,
  omie_hora_inclusao VARCHAR(8) NULL,
  omie_usuario_inclusao VARCHAR(80) NULL,
  omie_data_alteracao VARCHAR(10) NULL,
  omie_hora_alteracao VARCHAR(8) NULL,
  omie_usuario_alteracao VARCHAR(80) NULL,
  pagina_api INT NULL,
  total_de_paginas_api INT NULL,
  registros_api INT NULL,
  total_de_registros_api INT NULL,
  categorias_json JSON NOT NULL,
  distribuicao_json JSON NOT NULL,
  boleto_json JSON NOT NULL,
  info_json JSON NOT NULL,
  dados_json JSON NOT NULL,
  dados_flat_json JSON NOT NULL,
  extraido_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (codigo_lancamento_omie),
  KEY idx_raw_omie_cr_cliente (codigo_cliente_fornecedor),
  KEY idx_raw_omie_cr_categoria (codigo_categoria),
  KEY idx_raw_omie_cr_conta_corrente (id_conta_corrente),
  KEY idx_raw_omie_cr_projeto (codigo_projeto),
  KEY idx_raw_omie_cr_tipo_documento (codigo_tipo_documento),
  KEY idx_raw_omie_cr_status (status_titulo),
  KEY idx_raw_omie_cr_vencimento (data_vencimento),
  CONSTRAINT fk_raw_omie_cr_cliente
    FOREIGN KEY (codigo_cliente_fornecedor)
    REFERENCES raw_omie_clientes (codigo_cliente_omie)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
)
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS raw_omie_titulos_lancados (
  codigo_titulo BIGINT NOT NULL,
  codigo_titulo_repeticao BIGINT NULL,
  codigo_titulo_integracao VARCHAR(120) NULL,
  natureza CHAR(1) NULL,
  codigo_cliente BIGINT NOT NULL,
  cnpj_cpf_cliente VARCHAR(30) NULL,
  codigo_categoria VARCHAR(40) NULL,
  codigo_tipo_documento VARCHAR(20) NULL,
  id_conta_corrente BIGINT NULL,
  origem VARCHAR(20) NULL,
  numero_titulo VARCHAR(120) NULL,
  numero_documento_fiscal VARCHAR(120) NULL,
  numero_parcela VARCHAR(30) NULL,
  codigo_barras VARCHAR(255) NULL,
  observacao TEXT NULL,
  data_emissao VARCHAR(10) NULL,
  data_pagamento VARCHAR(10) NULL,
  data_previsao VARCHAR(10) NULL,
  data_registro VARCHAR(10) NULL,
  data_vencimento VARCHAR(10) NULL,
  valor_titulo DECIMAL(18, 4) NULL,
  valor_cofins DECIMAL(18, 4) NULL,
  valor_csll DECIMAL(18, 4) NULL,
  valor_inss DECIMAL(18, 4) NULL,
  valor_ir DECIMAL(18, 4) NULL,
  valor_iss DECIMAL(18, 4) NULL,
  valor_pis DECIMAL(18, 4) NULL,
  retem_cofins CHAR(1) NULL,
  retem_csll CHAR(1) NULL,
  retem_inss CHAR(1) NULL,
  retem_ir CHAR(1) NULL,
  retem_iss CHAR(1) NULL,
  retem_pis CHAR(1) NULL,
  status_titulo VARCHAR(40) NULL,
  liquidado CHAR(1) NULL,
  valor_aberto DECIMAL(18, 4) NULL,
  valor_liquido DECIMAL(18, 4) NULL,
  valor_pago DECIMAL(18, 4) NULL,
  valor_desconto DECIMAL(18, 4) NULL,
  valor_juros DECIMAL(18, 4) NULL,
  valor_multa DECIMAL(18, 4) NULL,
  primeiro_codigo_lancamento BIGINT NULL,
  primeiro_id_lancamento_cc BIGINT NULL,
  primeiro_codigo_lancamento_integracao VARCHAR(120) NULL,
  primeiro_data_lancamento VARCHAR(10) NULL,
  primeiro_valor_lancamento DECIMAL(18, 4) NULL,
  primeiro_observacao_lancamento TEXT NULL,
  primeiro_codigo_conta_corrente BIGINT NULL,
  pagina_api INT NULL,
  total_de_paginas_api INT NULL,
  registros_api INT NULL,
  total_de_registros_api INT NULL,
  cabec_titulo_json JSON NOT NULL,
  categorias_json JSON NOT NULL,
  departamentos_json JSON NOT NULL,
  lancamentos_json JSON NOT NULL,
  resumo_json JSON NOT NULL,
  dados_json JSON NOT NULL,
  dados_flat_json JSON NOT NULL,
  extraido_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (codigo_titulo),
  KEY idx_raw_omie_tl_cliente (codigo_cliente),
  KEY idx_raw_omie_tl_natureza (natureza),
  KEY idx_raw_omie_tl_categoria (codigo_categoria),
  KEY idx_raw_omie_tl_conta_corrente (id_conta_corrente),
  KEY idx_raw_omie_tl_status (status_titulo),
  KEY idx_raw_omie_tl_vencimento (data_vencimento),
  KEY idx_raw_omie_tl_titulo_repeticao (codigo_titulo_repeticao),
  KEY idx_raw_omie_tl_lancamento (primeiro_codigo_lancamento),
  CONSTRAINT fk_raw_omie_tl_cliente
    FOREIGN KEY (codigo_cliente)
    REFERENCES raw_omie_clientes (codigo_cliente_omie)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
)
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS raw_omie_movimentos_financeiros (
  chave_movimento VARCHAR(100) NOT NULL,
  codigo_titulo BIGINT NULL,
  codigo_titulo_vinculado BIGINT NULL,
  codigo_titulo_repeticao BIGINT NULL,
  codigo_titulo_integracao VARCHAR(120) NULL,
  codigo_cliente BIGINT NULL,
  cnpj_cpf_cliente VARCHAR(30) NULL,
  codigo_contrato BIGINT NULL,
  numero_contrato VARCHAR(120) NULL,
  codigo_ordem_servico BIGINT NULL,
  numero_ordem_servico VARCHAR(120) NULL,
  codigo_categoria VARCHAR(40) NULL,
  grupo VARCHAR(40) NULL,
  natureza CHAR(1) NULL,
  operacao VARCHAR(10) NULL,
  numero_documento_fiscal VARCHAR(120) NULL,
  numero_parcela VARCHAR(30) NULL,
  numero_titulo VARCHAR(120) NULL,
  origem VARCHAR(20) NULL,
  status_titulo VARCHAR(40) NULL,
  codigo_tipo_documento VARCHAR(20) NULL,
  data_emissao VARCHAR(10) NULL,
  data_pagamento VARCHAR(10) NULL,
  data_previsao VARCHAR(10) NULL,
  data_registro VARCHAR(10) NULL,
  data_vencimento VARCHAR(10) NULL,
  id_conta_corrente BIGINT NULL,
  valor_titulo DECIMAL(18, 4) NULL,
  valor_pis DECIMAL(18, 4) NULL,
  retem_pis CHAR(1) NULL,
  valor_cofins DECIMAL(18, 4) NULL,
  retem_cofins CHAR(1) NULL,
  valor_csll DECIMAL(18, 4) NULL,
  retem_csll CHAR(1) NULL,
  valor_ir DECIMAL(18, 4) NULL,
  retem_ir CHAR(1) NULL,
  valor_iss DECIMAL(18, 4) NULL,
  retem_iss CHAR(1) NULL,
  valor_inss DECIMAL(18, 4) NULL,
  retem_inss CHAR(1) NULL,
  codigo_projeto BIGINT NULL,
  observacao TEXT NULL,
  codigo_vendedor BIGINT NULL,
  codigo_comprador BIGINT NULL,
  codigo_barras VARCHAR(255) NULL,
  nsu VARCHAR(120) NULL,
  codigo_nota_fiscal BIGINT NULL,
  numero_boleto VARCHAR(120) NULL,
  chave_nfe VARCHAR(44) NULL,
  codigo_movimento_conta_corrente BIGINT NULL,
  valor_movimento_conta_corrente DECIMAL(18, 4) NULL,
  codigo_movimento_repeticao BIGINT NULL,
  desconto_movimento DECIMAL(18, 4) NULL,
  juros_movimento DECIMAL(18, 4) NULL,
  multa_movimento DECIMAL(18, 4) NULL,
  codigo_baixa BIGINT NULL,
  data_credito VARCHAR(10) NULL,
  data_conciliacao VARCHAR(10) NULL,
  hora_conciliacao VARCHAR(8) NULL,
  usuario_conciliacao VARCHAR(80) NULL,
  data_inclusao VARCHAR(10) NULL,
  hora_inclusao VARCHAR(8) NULL,
  usuario_inclusao VARCHAR(80) NULL,
  data_alteracao VARCHAR(10) NULL,
  hora_alteracao VARCHAR(8) NULL,
  usuario_alteracao VARCHAR(80) NULL,
  liquidado CHAR(1) NULL,
  valor_desconto DECIMAL(18, 4) NULL,
  valor_juros DECIMAL(18, 4) NULL,
  valor_multa DECIMAL(18, 4) NULL,
  valor_aberto DECIMAL(18, 4) NULL,
  valor_liquido DECIMAL(18, 4) NULL,
  valor_pago DECIMAL(18, 4) NULL,
  pagina_api INT NULL,
  total_de_paginas_api INT NULL,
  registros_api INT NULL,
  total_de_registros_api INT NULL,
  detalhes_json JSON NOT NULL,
  resumo_json JSON NOT NULL,
  categorias_json JSON NOT NULL,
  departamentos_json JSON NOT NULL,
  dados_json JSON NOT NULL,
  dados_flat_json JSON NOT NULL,
  extraido_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (chave_movimento),
  KEY idx_raw_omie_mf_titulo (codigo_titulo),
  KEY idx_raw_omie_mf_titulo_vinculado (codigo_titulo_vinculado),
  KEY idx_raw_omie_mf_cliente (codigo_cliente),
  KEY idx_raw_omie_mf_titulo_repeticao (codigo_titulo_repeticao),
  KEY idx_raw_omie_mf_categoria (codigo_categoria),
  KEY idx_raw_omie_mf_grupo (grupo),
  KEY idx_raw_omie_mf_natureza (natureza),
  KEY idx_raw_omie_mf_conta_corrente (id_conta_corrente),
  KEY idx_raw_omie_mf_contrato (codigo_contrato),
  KEY idx_raw_omie_mf_ordem_servico (codigo_ordem_servico),
  KEY idx_raw_omie_mf_nota_fiscal (codigo_nota_fiscal),
  KEY idx_raw_omie_mf_movimento_cc (codigo_movimento_conta_corrente),
  KEY idx_raw_omie_mf_status (status_titulo),
  KEY idx_raw_omie_mf_vencimento (data_vencimento),
  CONSTRAINT fk_raw_omie_mf_cliente
    FOREIGN KEY (codigo_cliente)
    REFERENCES raw_omie_clientes (codigo_cliente_omie)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  CONSTRAINT fk_raw_omie_mf_titulo
    FOREIGN KEY (codigo_titulo_vinculado)
    REFERENCES raw_omie_titulos_lancados (codigo_titulo)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
)
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;
